#!/usr/bin/env python3

# Testing the polynomial module generated by SWIG.

import polynomial
import numpy as np
import matplotlib.pyplot as plt

# Set up some coefficients:
b = np.array([1., 0., -0.5])

# Make a polynomial
p = polynomial.Polynomial1D(b)

# Set up some points:
X = np.linspace(-1., 1., 100)
evals = []

for x in X:
    evals.append( p.eval_diff(x,0) )

plt.plot(X, evals)
plt.show()
